# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  test-louislabs:
    image: joseluisq/static-web-server:2
    # ports:
    #   - 8787:80
    restart: always
    volumes:
      - $PWD/public:/public
    command: bash entry.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showcase-louislabs-http.rule=Host(`showcase.louislabs.com`)"
      - "traefik.http.routers.showcase-louislabs-http.entrypoints=web"
      - "traefik.http.routers.showcase-louislabs-http.middlewares=showcase-louislabs-https"
      - "traefik.http.middlewares.showcase-louislabs-https.redirectscheme.scheme=https"
      - "traefik.http.routers.showcase-louislabs-https.rule=Host(`showcase.louislabs.com`)"
      - "traefik.http.routers.showcase-louislabs-https.entrypoints=websecure"
      - "traefik.http.routers.showcase-louislabs-https.tls.certresolver=myresolver"
      - "traefik.http.services.showcase-louislabs-https.loadbalancer.server.port=8787"

networks:
  default:
    external:
      name: traefik-proxy-network
